ARM: rockchip_defconfig: Restore CONFIG_FRAME_WARN=1280
fix following error:
arch/arm/boot/compressed/atags_to_fdt.c:129:5: error:
stack frame size (1352) exceeds limit (1280) in 'atags_to_fdt' [-Werror,-Wframe-larger-than]

Workaround for arch/arm/boot/compressed/Makefile.

Fixes: d2bf1e4c77a7 ("ARM: rockchip_defconfig: Enable CONFIG_RFKILL_RK")
Signed-off-by: Tao Huang <huangtao@rock-chips.com>
Change-Id: I8803bce1e1a904f89e41bbf52b299c9a2481404a